name: Trigger auto deployment for container-app-wkpo5ixldbzqg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-wkpo5ixldbzqg-AutoDeployTrigger-76673a15-c49f-4d70-9408-6de1be9ac442.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPWKPO5IXLDBZQG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPWKPO5IXLDBZQG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPWKPO5IXLDBZQG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPWKPO5IXLDBZQG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPWKPO5IXLDBZQG_REGISTRY_PASSWORD }}
          containerAppName: container-app-wkpo5ixldbzqg
          resourceGroup: todonodejspgsqlgoogleauth89869b4a
          imageToBuild: default/[parameters('containerAppNamebackend')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


